apiVersion: v1
kind: Service
metadata:
  name: classifiermodel-service
spec:
  selector:
    app: classifiermodel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer 